user 도메인 생성 및 signUp 기능 구현
Na-vi-9/msa pull request #28
Opened 2024-12-11 16:11 UTC by SEJ123

## #️⃣ 연관된 이슈
- #8 
## 📝 Description
![image](https://github.com/user-attachments/assets/1c64987a-343a-4a52-8a9c-2256d3c1fa4f)

## 💬 To Reivewers
[auth](http://localhost:19091/auth/signUp)
auth에서 user로 전송된 데이터로 회원가입을 진행해서 이슈 번호를 8로 했습니다!

2024-12-12 01:51 UTC, rua0704 requested changes

2024-12-12 01:51 UTC, rua0704 commented on user/src/main/java/com/sparta/user/application/service/UserService.java
> +    @Transactional
로그인에 Transactional이 필요할까요? 
@Transactional과 @Transactional(readOnly = true)에 대해 조사해보시고 수정해주세요

2024-12-12 01:51 UTC, rua0704 commented on user/src/main/java/com/sparta/user/presentation/exception/CustomException.java
컨벤션에 있는 CustomException과 errorcode 사용법확인하시고 그대로 사용해주시면 좋겠습니다.

2024-12-12 01:51 UTC, rua0704 commented on user/src/main/java/com/sparta/user/presentation/request/UserSignInRequestDto.java
@data 사용 지양해주세요

2024-12-12 13:09 UTC, SEJ123 commented on user/src/main/java/com/sparta/user/application/service/UserService.java
> +    @Transactional
수정하겠습니다!

2024-12-12 13:09 UTC, SEJ123 commented on user/src/main/java/com/sparta/user/presentation/exception/CustomException.java
넵! 수정하겠습니다!

2024-12-12 17:08 UTC, SEJ123 commented on user/src/main/java/com/sparta/user/presentation/request/UserSignInRequestDto.java
넵! 수정하겠습니다!

2024-12-13 07:05 UTC, eleunadeu commented
서비스에서 builder 사용하시는 것보단 entity나 dto안에서 builder를 만들고 사용하시는 게 코드 중복을 줄이실 수 있어서 좋을 거 같습니다.

2024-12-16 01:47 UTC, merged